# Project: bgl_test
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = bgl_test.o ../bgl_core/fontconv.o ../bgl_core/fontmap.o ../bgl_core/lib.o ../bgl_core/regex.o ../bgl_core/burglish.o ../bgl_core/burmese.o ../bgl_core/dictionary.o $(RES)
LINKOBJ  = bgl_test.o ../bgl_core/fontconv.o ../bgl_core/fontmap.o ../bgl_core/lib.o ../bgl_core/regex.o ../bgl_core/burglish.o ../bgl_core/burmese.o ../bgl_core/dictionary.o $(RES)
LIBS =  -L"E:/Dev-Cpp/lib"  
INCS =  -I"E:/Dev-Cpp/include" 
CXXINCS =  -I"E:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"E:/Dev-Cpp/include/c++/3.4.2/backward"  -I"E:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"E:/Dev-Cpp/include/c++/3.4.2"  -I"E:/Dev-Cpp/include" 
BIN  = bgl_test.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bgl_test.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "bgl_test.exe" $(LIBS)

bgl_test.o: bgl_test.cpp
	$(CPP) -c bgl_test.cpp -o bgl_test.o $(CXXFLAGS)

../bgl_core/fontconv.o: ../bgl_core/fontconv.cpp
	$(CPP) -c ../bgl_core/fontconv.cpp -o ../bgl_core/fontconv.o $(CXXFLAGS)

../bgl_core/fontmap.o: ../bgl_core/fontmap.cpp
	$(CPP) -c ../bgl_core/fontmap.cpp -o ../bgl_core/fontmap.o $(CXXFLAGS)

../bgl_core/lib.o: ../bgl_core/lib.cpp
	$(CPP) -c ../bgl_core/lib.cpp -o ../bgl_core/lib.o $(CXXFLAGS)

../bgl_core/regex.o: ../bgl_core/regex.cpp
	$(CPP) -c ../bgl_core/regex.cpp -o ../bgl_core/regex.o $(CXXFLAGS)

../bgl_core/burglish.o: ../bgl_core/burglish.cpp
	$(CPP) -c ../bgl_core/burglish.cpp -o ../bgl_core/burglish.o $(CXXFLAGS)

../bgl_core/burmese.o: ../bgl_core/burmese.cpp
	$(CPP) -c ../bgl_core/burmese.cpp -o ../bgl_core/burmese.o $(CXXFLAGS)

../bgl_core/dictionary.o: ../bgl_core/dictionary.cpp
	$(CPP) -c ../bgl_core/dictionary.cpp -o ../bgl_core/dictionary.o $(CXXFLAGS)
